const customers = [
  {
    customer_id: "CUST_0389",
    email: "cust_0389@gmail.com",
    nama: "Customer CUST_0389",
    call_failure: 6,
    complains: 1,
    subscription_length: 30,
    charge_amount: 1,
    seconds_of_use: 1495,
    frequency_of_use: 44,
    frequency_of_sms: 204,
    distinct_called_numbers: 16,
    age_group: 2,
    tariff_plan: 2,
    status: 1,
    age: 25,
    customer_value: 987.255,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "High",
  },
  {
    customer_id: "CUST_0478",
    email: "cust_0478@gmail.com",
    nama: "Customer CUST_0478",
    call_failure: 13,
    complains: 1,
    subscription_length: 36,
    charge_amount: 0,
    seconds_of_use: 2868,
    frequency_of_use: 54,
    frequency_of_sms: 55,
    distinct_called_numbers: 46,
    age_group: 3,
    tariff_plan: 1,
    status: 2,
    age: 30,
    customer_value: 336.88,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "Medium",
  },
  {
    customer_id: "CUST_0689",
    email: "cust_0689@gmail.com",
    nama: "Customer CUST_0689",
    call_failure: 6,
    complains: 1,
    subscription_length: 27,
    charge_amount: 1,
    seconds_of_use: 1505,
    frequency_of_use: 37,
    frequency_of_sms: 202,
    distinct_called_numbers: 14,
    age_group: 2,
    tariff_plan: 2,
    status: 1,
    age: 25,
    customer_value: 978.39,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "High",
  },
  {
    customer_id: "CUST_0989",
    email: "cust_0989@gmail.com",
    nama: "Customer CUST_0989",
    call_failure: 4,
    complains: 1,
    subscription_length: 27,
    charge_amount: 1,
    seconds_of_use: 1315,
    frequency_of_use: 36,
    frequency_of_sms: 193,
    distinct_called_numbers: 11,
    age_group: 2,
    tariff_plan: 2,
    status: 1,
    age: 25,
    customer_value: 929.295,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "High",
  },
  {
    customer_id: "CUST_0678",
    email: "cust_0678@gmail.com",
    nama: "Customer CUST_0678",
    call_failure: 11,
    complains: 1,
    subscription_length: 36,
    charge_amount: 0,
    seconds_of_use: 2458,
    frequency_of_use: 45,
    frequency_of_sms: 43,
    distinct_called_numbers: 34,
    age_group: 3,
    tariff_plan: 1,
    status: 2,
    age: 30,
    customer_value: 272.12,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "Medium",
  },
  {
    customer_id: "CUST_0477",
    email: "cust_0477@gmail.com",
    nama: "Customer CUST_0477",
    call_failure: 13,
    complains: 1,
    subscription_length: 35,
    charge_amount: 0,
    seconds_of_use: 3590,
    frequency_of_use: 51,
    frequency_of_sms: 30,
    distinct_called_numbers: 31,
    age_group: 3,
    tariff_plan: 1,
    status: 2,
    age: 30,
    customer_value: 265.64,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "Medium",
  },
  {
    customer_id: "CUST_0178",
    email: "cust_0178@gmail.com",
    nama: "Customer CUST_0178",
    call_failure: 10,
    complains: 1,
    subscription_length: 40,
    charge_amount: 0,
    seconds_of_use: 2348,
    frequency_of_use: 46,
    frequency_of_sms: 44,
    distinct_called_numbers: 35,
    age_group: 3,
    tariff_plan: 1,
    status: 2,
    age: 30,
    customer_value: 271.76,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "Medium",
  },
  {
    customer_id: "CUST_2673",
    email: "cust_2673@gmail.com",
    nama: "Customer CUST_2673",
    call_failure: 28,
    complains: 1,
    subscription_length: 36,
    charge_amount: 0,
    seconds_of_use: 1375,
    frequency_of_use: 59,
    frequency_of_sms: 55,
    distinct_called_numbers: 23,
    age_group: 3,
    tariff_plan: 1,
    status: 2,
    age: 30,
    customer_value: 277.36,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "Medium",
  },
  {
    customer_id: "CUST_0878",
    email: "cust_0878@gmail.com",
    nama: "Customer CUST_0878",
    call_failure: 15,
    complains: 1,
    subscription_length: 37,
    charge_amount: 0,
    seconds_of_use: 2978,
    frequency_of_use: 55,
    frequency_of_sms: 42,
    distinct_called_numbers: 31,
    age_group: 3,
    tariff_plan: 1,
    status: 2,
    age: 30,
    customer_value: 289.32,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "Medium",
  },
  {
    customer_id: "CUST_2577",
    email: "cust_2577@gmail.com",
    nama: "Customer CUST_2577",
    call_failure: 18,
    complains: 1,
    subscription_length: 37,
    charge_amount: 0,
    seconds_of_use: 3895,
    frequency_of_use: 57,
    frequency_of_sms: 37,
    distinct_called_numbers: 33,
    age_group: 3,
    tariff_plan: 1,
    status: 2,
    age: 30,
    customer_value: 306.08,
    segment: "Price-Sensitive / Low-Value Users",
    segment_description: "Lower-value customers suited for efficient lifecycle campaigns.",
    suggested_strategy: "Use low-cost automated offers and monitor response.",
    customer_value_tier: "Medium",
  },
];

return customers.map((customer) => ({ json: customer }));

